// Generated by FlutterFire CLI (placeholder).
//
// Run `flutterfire configure` and replace this file.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

abstract final class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (!kIsWeb) {
      throw StateError(
        'Missing native Firebase configs. Add google-services.json / '
        'GoogleService-Info.plist or run flutterfire configure.',
      );
    }

    return const FirebaseOptions(
      apiKey: 'REPLACE_ME',
      appId: 'REPLACE_ME',
      messagingSenderId: 'REPLACE_ME',
      projectId: 'REPLACE_ME',
    );
  }
}

