// Generated by FlutterFire CLI (placeholder).
//
// Run `flutterfire configure` and replace this file.

import 'package:firebase_core/firebase_core.dart';

abstract final class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Admin is web-first, so options are required even for local dev.
    return const FirebaseOptions(
      apiKey: 'REPLACE_ME',
      appId: 'REPLACE_ME',
      messagingSenderId: 'REPLACE_ME',
      projectId: 'REPLACE_ME',
    );
  }
}

