// Generated by FlutterFire CLI.
//
// This placeholder exists so the repo compiles before you run:
//   flutterfire configure
//
// After running, replace this file with the generated one.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

abstract final class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (!kIsWeb) {
      throw StateError(
        'Missing native Firebase configs. Add google-services.json / '
        'GoogleService-Info.plist or run flutterfire configure.',
      );
    }

    // Web requires explicit options. Replace with generated values.
    return const FirebaseOptions(
      apiKey: 'REPLACE_ME',
      appId: 'REPLACE_ME',
      messagingSenderId: 'REPLACE_ME',
      projectId: 'REPLACE_ME',
    );
  }
}

