import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Centralized Firebase initialization.
///
/// For Android/iOS, native config files are required:
/// - `google-services.json` (Android)
/// - `GoogleService-Info.plist` (iOS)
///
/// For Web, you must pass explicit [options] (generated by FlutterFire).
abstract final class FirebaseBootstrap {
  static Future<FirebaseApp> ensureInitialized({
    FirebaseOptions? options,
  }) async {
    if (Firebase.apps.isNotEmpty) return Firebase.apps.first;

    if (kIsWeb) {
      if (options == null) {
        throw StateError(
          'FirebaseOptions are required on Web. Run `flutterfire configure` '
          'and pass DefaultFirebaseOptions.currentPlatform.',
        );
      }
      return Firebase.initializeApp(options: options);
    }

    return Firebase.initializeApp();
  }
}

